// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXYG-NM0YD4odwa0WmkmkfbRmfDeEb2ns',
    appId: '1:447340509164:web:89ae43de89876657a0f2c9',
    messagingSenderId: '447340509164',
    projectId: 'recipbook-5ed02',
    authDomain: 'recipbook-5ed02.firebaseapp.com',
    storageBucket: 'recipbook-5ed02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQW_4cyFF1_P5On0RztWhidnD4K58_uc',
    appId: '1:447340509164:android:33354ac60d412512a0f2c9',
    messagingSenderId: '447340509164',
    projectId: 'recipbook-5ed02',
    storageBucket: 'recipbook-5ed02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpsy84m74-Q4zAJbMt3F2Vw5YXMcl0M_s',
    appId: '1:447340509164:ios:5c2741c81b8dd267a0f2c9',
    messagingSenderId: '447340509164',
    projectId: 'recipbook-5ed02',
    storageBucket: 'recipbook-5ed02.firebasestorage.app',
    iosBundleId: 'com.example.recepiesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpsy84m74-Q4zAJbMt3F2Vw5YXMcl0M_s',
    appId: '1:447340509164:ios:5c2741c81b8dd267a0f2c9',
    messagingSenderId: '447340509164',
    projectId: 'recipbook-5ed02',
    storageBucket: 'recipbook-5ed02.firebasestorage.app',
    iosBundleId: 'com.example.recepiesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXYG-NM0YD4odwa0WmkmkfbRmfDeEb2ns',
    appId: '1:447340509164:web:182f5286ac658f69a0f2c9',
    messagingSenderId: '447340509164',
    projectId: 'recipbook-5ed02',
    authDomain: 'recipbook-5ed02.firebaseapp.com',
    storageBucket: 'recipbook-5ed02.firebasestorage.app',
  );
}
